<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckOutDate</name>
   <tag></tag>
   <elementGuidId>c57ad1ce-b7b5-499e-99df-6172242bf324</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepick_out</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datepick_out']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a8fb3d2-5a5e-446e-82e5-98085b775989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datepick_out</value>
      <webElementGuid>c9227b3c-8969-4760-9c48-f6cee7164db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20e357d9-06b5-422b-961e-4bada13e5fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date_pick</value>
      <webElementGuid>b76f5993-2966-4484-85f5-e73dc8868a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepick_out</value>
      <webElementGuid>16e6e8bc-0331-4512-be24-cdede660c4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>25/01/2023</value>
      <webElementGuid>eb095370-1cc6-453e-9c67-61b90d486774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>71c3ea12-0290-4503-8109-e00fa0af02ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepick_out&quot;)</value>
      <webElementGuid>bdf0bebc-62f1-45a6-98e0-753e5b5ac40d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datepick_out']</value>
      <webElementGuid>5de18507-fd8b-43bf-9d9a-3ff99cd04472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>7d0a5e66-ed14-4505-b367-2cd1ad9e027e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>06045338-ba24-4913-bc36-a48c80489667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'datepick_out' and @type = 'text' and @id = 'datepick_out']</value>
      <webElementGuid>12deaa6f-b5a7-479e-9de9-cf9aab971f9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
