<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckInDate</name>
   <tag></tag>
   <elementGuidId>f96d6c07-cf45-4ec1-b687-c5cda704f498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datepick_in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datepick_in']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73fcac6d-d3e0-40d2-96e2-77c789da5712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datepick_in</value>
      <webElementGuid>70145a95-0a82-409f-90b8-e9795c6dd997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb0d09ef-8c73-479b-9044-781ce6fc01e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date_pick</value>
      <webElementGuid>e8d0e345-89f3-4170-aa9c-8bf77eb5ab4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datepick_in</value>
      <webElementGuid>8bcf01e6-9d1e-42df-9ab2-8012177c6c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>24/01/2023</value>
      <webElementGuid>0d3d58b9-3912-4729-a832-0ca31ca66b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f7f8bc93-ffca-4c81-9ed6-9f9607eef996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datepick_in&quot;)</value>
      <webElementGuid>2630a6f4-33eb-46c0-b6f3-5b2010074e57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datepick_in']</value>
      <webElementGuid>7049272b-7912-4b01-9869-4b1af4f2315f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>3e82bbe0-4f01-408e-bd64-b1e51899ccd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>5f864c9d-cd49-4258-9382-f80cc84adcfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'datepick_in' and @type = 'text' and @id = 'datepick_in']</value>
      <webElementGuid>55b4f1ab-3196-49c7-8ef8-bae960f42986</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
