<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ResetButton</name>
   <tag></tag>
   <elementGuidId>c95cb898-d4ca-484f-9b6f-7c6bb1a5f665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Reset</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Reset']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe36a2fc-e541-427d-bd1d-809d2a9a895e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>reset</value>
      <webElementGuid>b12bc1b2-17ef-4009-b907-bccf98a20aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Reset</value>
      <webElementGuid>ffae0424-ea49-4444-afbd-5e6f0ce0f7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Reset</value>
      <webElementGuid>d34812eb-18a6-4891-9101-560b47429064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_button</value>
      <webElementGuid>0b2e1cb3-8e2b-4bd1-9021-9db78592caa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Reset</value>
      <webElementGuid>0967ae6b-0179-4675-992a-fe3c43eaec02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reset&quot;)</value>
      <webElementGuid>d4b4d8ab-46b1-4e07-a5ef-03550acb095c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Reset']</value>
      <webElementGuid>143f22f4-1b59-4b98-a478-b27164861e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/table/tbody/tr[10]/td[2]/input[2]</value>
      <webElementGuid>a0d7574f-ffc8-4afd-ba45-62f9d44c97df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>9ceb61eb-6b6d-4d90-8c51-fa1cfd67b258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'reset' and @name = 'Reset' and @id = 'Reset']</value>
      <webElementGuid>b3913b00-430b-4796-8713-5494f4bbfc90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
