<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BookNowButton</name>
   <tag></tag>
   <elementGuidId>ca26ab2c-ff1a-4cb4-838d-b1136f41b991</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#book_now</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='book_now']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec8f4a25-a24f-4a7f-a4b8-513ce7dd3272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc85ede6-329c-43a5-8e7e-3296f07cee79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>book_now</value>
      <webElementGuid>f9b4a061-e585-4d4e-a2f9-93758eb706d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>book_now</value>
      <webElementGuid>d650e91f-546f-4b2a-aee7-594ee4242e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_button</value>
      <webElementGuid>39059267-2058-49e3-a0a8-12fffef7a26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Book Now</value>
      <webElementGuid>25be5298-df92-40e2-8be6-e8de0a5c90db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>book_hotel_validate();</value>
      <webElementGuid>115df9e2-a77c-4314-9b72-f0d2c89447a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;book_now&quot;)</value>
      <webElementGuid>c5cfc3b9-9183-4a86-b223-8aa03bb9d566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='book_now']</value>
      <webElementGuid>55ce0846-ce93-427b-b704-9c937bda904f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[19]/td[2]/input</value>
      <webElementGuid>1f709f7b-229f-4496-8e63-dddf17f6b114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[2]/input</value>
      <webElementGuid>8d25c40e-dd43-4bad-a895-2897d7f8b753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'book_now' and @id = 'book_now']</value>
      <webElementGuid>dc91dc93-01e5-435d-a528-be212e4d2ff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
