<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CVVNumber</name>
   <tag></tag>
   <elementGuidId>f1377e8e-d733-451c-a2d4-01bb34f673da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cc_cvv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cc_cvv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8b930b3-6acd-4fe5-958e-e520987e687e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cc_cvv</value>
      <webElementGuid>ad4d7c34-2869-4e45-ba9c-5629ec1da39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d2c190c-c748-4e72-a3bb-e2d8a9abccb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_input</value>
      <webElementGuid>d72cee47-4a9c-4d45-827d-7ead11bb11b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc_cvv</value>
      <webElementGuid>c2b86ac6-e93b-4620-b397-505538aeb9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>233f2d47-f037-4a65-b06a-9953d4d475f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return OnlyNumbersonly(event)</value>
      <webElementGuid>ec972045-70f6-4f95-acad-9f34df22bb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc_cvv&quot;)</value>
      <webElementGuid>6ad8b8e4-6aa9-4702-8d94-28d67c78ff43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cc_cvv']</value>
      <webElementGuid>6662349e-95ab-4586-84a0-45e6432a9608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[18]/td[2]/input</value>
      <webElementGuid>7bfc71df-8422-4fc9-8420-df4628acc32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[2]/input</value>
      <webElementGuid>be12c397-743b-4856-910d-babc94cf99e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cc_cvv' and @type = 'text' and @id = 'cc_cvv']</value>
      <webElementGuid>05fb4568-99ef-4097-b48c-ee28cdd87e52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
