<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExpiryDate_Month</name>
   <tag></tag>
   <elementGuidId>af78724e-aacf-42fc-9e86-6a355d2bf9c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cc_exp_month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cc_exp_month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>47cef526-1d72-4de5-b533-1317e2acac96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cc_exp_month</value>
      <webElementGuid>c5592777-08a3-4b5d-955f-f7820e910664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc_exp_month</value>
      <webElementGuid>2a71365f-08d7-445a-ba4a-948263214c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_combobox2</value>
      <webElementGuid>9e6d0439-74cd-481e-97d2-fd5fa7044691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            - Select Month -
            January
            February
            March
			April
			May
			June
			July
			August
			September
			October
			November
            December
          </value>
      <webElementGuid>807e0091-d952-439e-a8ac-1c539433d6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc_exp_month&quot;)</value>
      <webElementGuid>59713545-09c9-4942-a583-672a91fa25ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cc_exp_month']</value>
      <webElementGuid>9bd61d84-a942-44d0-a309-83404481194f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[17]/td[2]/select</value>
      <webElementGuid>a19cf7bc-955d-469a-9c69-94f1189fb190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>395af26e-2f5f-4071-94bf-544ec2fa519e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[2]</value>
      <webElementGuid>0c6131ab-62c8-41ad-acf4-3e77dc13d818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[2]/select</value>
      <webElementGuid>77c45782-0329-4485-b28a-4a08f8ec2ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cc_exp_month' and @id = 'cc_exp_month' and (text() = '
            - Select Month -
            January
            February
            March
			April
			May
			June
			July
			August
			September
			October
			November
            December
          ' or . = '
            - Select Month -
            January
            February
            March
			April
			May
			June
			July
			August
			September
			October
			November
            December
          ')]</value>
      <webElementGuid>af2994ba-e7d5-4fec-9624-a4a8548a0aab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
