<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExpiryDate_Year</name>
   <tag></tag>
   <elementGuidId>4ae606e1-2c92-46e5-8920-a1f46eea53ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cc_exp_year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cc_exp_year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ed584da6-ad13-43a1-a30b-2f7872adb609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cc_exp_year</value>
      <webElementGuid>c769629c-3139-4b0d-a7c4-a4c5d81703eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc_exp_year</value>
      <webElementGuid>3c505aef-9d21-482d-ba1e-0a4d3d82c824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_combobox2</value>
      <webElementGuid>8630420d-8ac6-41d5-b75f-0006e160ab11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            - Select Year -
            2011
			2012
            2013
            2014
            2015
			2016
			2017
			2018
			2019
			2020
			2021
			2022
          </value>
      <webElementGuid>40d46854-f380-434f-8b1f-ad6c5c5b99ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc_exp_year&quot;)</value>
      <webElementGuid>8bceebae-1ce9-43af-bdfa-26e1d4d4427e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cc_exp_year']</value>
      <webElementGuid>61bfd05d-35f7-419c-93b4-31cae8cfe29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[17]/td[2]/select[2]</value>
      <webElementGuid>496ffee6-2a13-4103-b20a-4eeff546c693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[2]</value>
      <webElementGuid>1bfd4aee-021c-4098-b5a5-1824b2938e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>5f32671f-860b-4c8b-aad2-77b880d64746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>f730cfc2-527b-4cf1-8d3f-430bc8832114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cc_exp_year' and @id = 'cc_exp_year' and (text() = '
            - Select Year -
            2011
			2012
            2013
            2014
            2015
			2016
			2017
			2018
			2019
			2020
			2021
			2022
          ' or . = '
            - Select Year -
            2011
			2012
            2013
            2014
            2015
			2016
			2017
			2018
			2019
			2020
			2021
			2022
          ')]</value>
      <webElementGuid>3f70509b-cc78-4c26-ad08-ce24c0030c62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
