<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FirstName</name>
   <tag></tag>
   <elementGuidId>52054dcf-52ec-4d62-8769-02610944afd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1be325d-49cc-40d7-9f3e-bd06cb03ddc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>first_name</value>
      <webElementGuid>aa914ace-27a2-4411-b6d6-1023f8e899a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>695b2363-f63a-44a9-a484-317e01f4f774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_input</value>
      <webElementGuid>66e6b806-32c6-4063-9a09-9be7a961b172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>first_name</value>
      <webElementGuid>a581e253-40e0-4669-821b-c9f7aae8f6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>1baafb2c-6d6d-4cd8-bea5-a63da1052fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;first_name&quot;)</value>
      <webElementGuid>90914a95-50cc-4ac8-96c4-ae4dcb4b6ea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='first_name']</value>
      <webElementGuid>a96a4b98-5d50-4c52-af7b-354ae385da86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>1474cfba-3e50-40ac-973e-51c0d32f0b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[2]/input</value>
      <webElementGuid>bbb589a4-df2e-4c0a-b481-78af96a35ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'first_name' and @type = 'text' and @id = 'first_name']</value>
      <webElementGuid>f69a4f2d-35e5-4f6f-8e25-3f983049ea2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
