<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CancelButton</name>
   <tag></tag>
   <elementGuidId>ffbc36f0-9592-4f9e-9c77-42f3eff52a29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cancel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cancel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05db2ed8-0934-436a-bd5c-e7a7b03a0bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4dc748e4-fb3a-4074-9234-1fbb81469601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cancel</value>
      <webElementGuid>8744ec7b-0f21-455f-aac1-c538c0436655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancel</value>
      <webElementGuid>3b221e1c-823a-48e3-a1c2-b13dc5f28c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_button</value>
      <webElementGuid>46bf4889-51e7-4e54-86df-31c5329a6386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>ae0f2fbb-55a1-4f72-8274-ba41a7c68d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.location=&quot;SearchHotel.php&quot;</value>
      <webElementGuid>77b91253-0913-44d5-835a-934b1c1aceee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancel&quot;)</value>
      <webElementGuid>d2d1ae88-2161-472d-94b4-feec9b16542e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cancel']</value>
      <webElementGuid>cd3c7089-ed42-4771-9f97-f3f71e2ee4a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='select_form']/table/tbody/tr[3]/td/input[2]</value>
      <webElementGuid>5090c2d0-4119-4ec2-9207-fffdec75c2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input[2]</value>
      <webElementGuid>f125bd00-7da9-457c-971a-968dcc266e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'cancel' and @id = 'cancel']</value>
      <webElementGuid>d6f62392-972a-4ea1-b688-b07a0ccbeaad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
