<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MsgIfHotelNotSelected_Please Select a Hotel</name>
   <tag></tag>
   <elementGuidId>0ad721a2-b158-47f1-a8ab-9ce1fcec8ad8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radiobutton_span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='radiobutton_span']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d6a92d28-7934-4c2c-83a0-607d29525029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radiobutton_span</value>
      <webElementGuid>1736d4cb-9883-4709-9eb3-deec8a624edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_error</value>
      <webElementGuid>c7aedebb-9191-4464-b705-275c1e8a6225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select a Hotel</value>
      <webElementGuid>dc1d6bf4-74ad-47fe-8ed2-b2296a093746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radiobutton_span&quot;)</value>
      <webElementGuid>2dfd12b0-c541-41d6-9d2b-7d4520c972d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='radiobutton_span']</value>
      <webElementGuid>e01f9050-ae3a-43c2-b89d-74abc05ed553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='select_form']/table/tbody/tr[3]/td/label</value>
      <webElementGuid>1774ba15-ceb0-4606-b5e6-29868b6b248c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Price (excl. GST)'])[1]/following::label[1]</value>
      <webElementGuid>11ea3b05-596e-47bb-8836-139b25436b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price per Night'])[1]/following::label[1]</value>
      <webElementGuid>56784cd7-ea4d-4857-bcb5-0547ea171fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adactin.com'])[1]/preceding::label[1]</value>
      <webElementGuid>a89e55d1-26bb-4742-b9c0-abd4c2b2c72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please Select a Hotel']/parent::*</value>
      <webElementGuid>23749070-bf66-472b-8e31-cda6bb6b6c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>4265d963-22f3-4e5e-a068-c836b40f9a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'radiobutton_span' and (text() = 'Please Select a Hotel' or . = 'Please Select a Hotel')]</value>
      <webElementGuid>9d162167-1545-4bab-b783-a18582d4df67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
