<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RadioButtonForSelectionHotel</name>
   <tag></tag>
   <elementGuidId>0245faba-702d-42e1-82c7-9473a4f7a94d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radiobutton_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radiobutton_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dc3005f-c78e-4d1d-97c6-d8c5aed213d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radiobutton_0</value>
      <webElementGuid>090d3729-b1b0-4b8b-8be5-1c3dffa73608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radiobutton_0</value>
      <webElementGuid>ebfc702f-601b-46f7-8c53-c4c0c9442fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>96510bab-f091-41ba-b5d3-0bac2cdbc1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>429288b7-a5fa-4930-aa44-c68c984170c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radiobutton_0&quot;)</value>
      <webElementGuid>9e5789c0-a2ca-44ab-8c71-64b4ea893a5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radiobutton_0']</value>
      <webElementGuid>956abd63-0b08-41e1-855c-f06a032c8689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='select_form']/table/tbody/tr[2]/td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>2a66cbd4-8884-4672-90b3-d037efc63060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8d338694-9c9e-41f6-9f53-dc6b5400e24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'radiobutton_0' and @id = 'radiobutton_0' and @type = 'radio']</value>
      <webElementGuid>46f4c7d3-8d09-40c1-bd18-ff68ff64d636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
